/********************************************************************************
 *        Copyright(c) 2014-2016 Actions (Zhuhai) Technology Co., Limited,
 *                            All Rights Reserved.
 *
 * 描述：ASET音效调试协议命令ID定义。
 * 作者：cailizhen
 ********************************************************************************/

#ifndef __COMMON_ASET_COMMAND_H
#define __COMMON_ASET_COMMAND_H

#include "psp_includes.h"


//新版ASET工具命令字

//Read Staus
#define STUB_CMD_ASET_READ_STATUS       (0x0300)

#define STUB_CMD_ASET_WRITE_STATUS      (0x0380)

//Read Volume
#define STUB_CMD_ASET_READ_VOLUME       (0x0301)

#define STUB_CMD_ASET_WRITE_VOLUME      (0x0381)

#define STUB_CMD_ASET_READ_EQ_DATA      (0x0302)

#define STUB_CMD_ASET_WRITE_EQ_DATA     (0x0382)

#define STUB_CMD_ASET_READ_VBASS_DATA   (0x0303)

#define STUB_CMD_ASET_WRITE_VBASS_DATA  (0x0383)

#define STUB_CMD_ASET_READ_TE_DATA      (0x0304)

#define STUB_CMD_ASET_WRITE_TE_DATA     (0x0384)

#define STUB_CMD_ASET_READ_SURR_DATA    (0x0305)

#define STUB_CMD_ASET_WRITE_SURR_DATA   (0x0385)

#define STUB_CMD_ASET_READ_LIMITER_DATA (0x0306)

#define STUB_CMD_ASET_WRITE_LIMITER_DATA (0x0386)

#define STUB_CMD_ASET_READ_SPKCMP_DATA  (0x0307)

#define STUB_CMD_ASET_WRITE_SPKCMP_DATA (0x0387)

#define STUB_CMD_ASET_READ_MDRC_DATA    (0x0308)

#define STUB_CMD_ASET_WRITE_MDRC_DATA   (0x0388)

#define STUB_CMD_ASET_READ_MDRC2_DATA   (0x0309)

#define STUB_CMD_ASET_WRITE_MDRC2_DATA  (0x0389)




#define STUB_CMD_ASET_READ_SEE_DATA     (0x030C)

#define STUB_CMD_ASET_WRITE_SEE_DATA    (0x038C)

#define STUB_CMD_ASET_READ_SEW_DATA     (0x030D)

#define STUB_CMD_ASET_WRITE_SEW_DATA    (0x038D)

#define STUB_CMD_ASET_READ_SD_DATA      (0x030E)

#define STUB_CMD_ASET_WRITE_SD_DATA     (0x038E)

#define STUB_CMD_ASET_SWTICH_AUX_MODE   (0x0390)

#define STUB_CMD_ASET_READ_LFRC_DATA_BASE    (0x0311)

#define STUB_CMD_ASET_WRITE_LFRC_DATA_BASE   (0x0391)

#define STUB_CMD_ASET_READ_LFRC1_DATA   (STUB_CMD_ASET_READ_LFRC_DATA_BASE)

#define STUB_CMD_ASET_WRITE_LFRC1_DATA  (STUB_CMD_ASET_WRITE_LFRC_DATA_BASE)

#define STUB_CMD_ASET_READ_LFRC2_DATA   (STUB_CMD_ASET_READ_LFRC_DATA_BASE+1)

#define STUB_CMD_ASET_WRITE_LFRC2_DATA  (STUB_CMD_ASET_WRITE_LFRC_DATA_BASE+1)

#define STUB_CMD_ASET_READ_LFRC3_DATA   (STUB_CMD_ASET_READ_LFRC_DATA_BASE+2)

#define STUB_CMD_ASET_WRITE_LFRC3_DATA  (STUB_CMD_ASET_WRITE_LFRC_DATA_BASE+2)

#define STUB_CMD_ASET_READ_LFRC4_DATA   (STUB_CMD_ASET_READ_LFRC_DATA_BASE+3)

#define STUB_CMD_ASET_WRITE_LFRC4_DATA  (STUB_CMD_ASET_WRITE_LFRC_DATA_BASE+3)



#define STUB_CMD_ASET_READ_RFRC_DATA_BASE    (0x0315)

#define STUB_CMD_ASET_WRITE_RFRC_DATA_BASE   (0x0395)


#define STUB_CMD_ASET_READ_RFRC1_DATA   (STUB_CMD_ASET_READ_RFRC_DATA_BASE)

#define STUB_CMD_ASET_WRITE_RFRC1_DATA  (STUB_CMD_ASET_WRITE_RFRC_DATA_BASE)

#define STUB_CMD_ASET_READ_RFRC2_DATA   (STUB_CMD_ASET_READ_RFRC_DATA_BASE+1)

#define STUB_CMD_ASET_WRITE_RFRC2_DATA  (STUB_CMD_ASET_WRITE_RFRC_DATA_BASE+1)

#define STUB_CMD_ASET_READ_RFRC3_DATA   (STUB_CMD_ASET_READ_RFRC_DATA_BASE+2)

#define STUB_CMD_ASET_WRITE_RFRC3_DATA  (STUB_CMD_ASET_WRITE_RFRC_DATA_BASE+2)

#define STUB_CMD_ASET_READ_RFRC4_DATA   (STUB_CMD_ASET_READ_RFRC_DATA_BASE+3)

#define STUB_CMD_ASET_WRITE_RFRC4_DATA  (STUB_CMD_ASET_WRITE_RFRC_DATA_BASE+3)


#define STUB_CMD_ASET_READ_MAIN_SWITCH  (0x0319)

#define STUB_CMD_ASET_READ_EQ2_DATA     (0x0321)
#define STUB_CMD_ASET_READ_EQ3_DATA     (0x0322)

#define STUB_CMD_ASET_READ_DRC2_DATA    (0x032c)

#define STUB_CMD_ASET_ACK               (0x03fe)

#endif

