 /* generated by ResBuilder, (c)2003 Actions */
/******************************************/
#ifndef _LANG_ID
#define _LANG_ID

#define CHINESE_SIMPLIFIED  		0
#define ENGLISH             		1
#define CHINESE_TRADITIONAL 		2
#define JAPANESE            		3
#define KOREAN              		4
#define FRENCH              		5
#define GERMAN              		6
#define ITALIAN             		7
#define DUTCH               		8
#define PORTUGUESE          		9
#define SPANISH             		10
#define SWEDISH             		11
#define CZECH               		12
#define DANISH              		13
#define POLISH              		14
#define RUSSIAN             		15
#define TURKISH             		16
#define HEBREW              		17
#define THAI                		18
#define HUNGARIAN           		19
#define ROMANIAN            		20
#define ARABIC              		21
#define INDONESIAN          		22
#define GREEK               		23
#endif
